AnimeApp/Models/Anime.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AnimeApp.Models
{
    public class Anime
    {
        [Key]
        public int AnimeId { get; set; }


        [Required]
        [MaxLength(100)]
        public string Title { get; set; }

        [Required]
        [MaxLength(500)]
        public string Description { get; set; }

        [Required]
        [Display(Name ="Release Year")]
        public int ReleaseYear { get; set; } = 1901;
        public List<ApplicationUser> UsersWatched { get; } = new();

        [Required]
        [NotMapped]
        public IFormFile Cover { get; set; }
        public string CoverUrl { get; set; } = "";
        public Anime() { }
    }
}

AnimeApp/Controllers/AnimesController.cs
using AnimeApp.Data;
using AnimeApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnimeApp.Controllers
{
    public class AnimesController : Controller
    {
        private readonly ApplicationDbContext _db;
        private UserManager<ApplicationUser> _userManager;
        public AnimesController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Index(string searchString)
        {

            var animes = from a in _db.Animes
                         select a;

            if(!String.IsNullOrEmpty(searchString))
            {
                animes = animes.Where(b => b.Title.ToLower().Contains(searchString.ToLower()));
            }

            ViewData["CurrentSearchString"] = searchString;

            return View(animes);
        }

        [Route("animes/{animeId}")]    
        public async Task<IActionResult> Anime(int animeId)
        {
            var anime = await _db.Animes.FirstOrDefaultAsync(a=>a.AnimeId == animeId);

            if(anime == null)
            {
                return NotFound();
            }
            return View(anime);
        }

        [Authorize]
        [Route("/animes/add_anime_to_user/{animeId}")]
        public async Task<JsonResult> AddAnimeToUser(int animeId)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var anime = _db.Animes.First(a => a.AnimeId == animeId);

                AnimeApplicationUser relationship = new AnimeApplicationUser(anime, user);

                if (user == null || anime == null)
                {
                    return new JsonResult(new { result = false });
                }

                await _db.AnimeApplicationUsers.AddAsync(relationship);
                await _db.SaveChangesAsync();
            }
            catch (Exception)
            {
                throw;
            }
            return new JsonResult(new { result = true });
        }

        [Authorize]
        [Route("/animes/remove_anime_from_user/{animeId}")]
        public async Task<JsonResult> RemoveAnimeFromUser(int animeId)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var result = await _db.AnimeApplicationUsers.FirstOrDefaultAsync(r => (r.AnimeId == animeId && r.ApplicationUser.Id == user.Id));

                _db.AnimeApplicationUsers.Remove(result);
                await _db.SaveChangesAsync();

            }
            catch (Exception)
            {
                throw;
            }
            return new JsonResult(new { result = true });
        }

        [Authorize]
        [Route("/animes/check_user_anime/{animeId}")]
        public async Task<JsonResult> CheckUserAnime(int animeId) 
        {
            var user = await _userManager.GetUserAsync(User);
            var result = await _db.AnimeApplicationUsers.FirstOrDefaultAsync(r => (r.AnimeId == animeId && r.ApplicationUser.Id == user.Id));

            if (result == null)
            {
                return new JsonResult(new { watched = false });
            }

            return new JsonResult(new { watched = true }); ;
        }
    }
}

AnimeApp/Views/Animes/Anime.cshtml
@using Microsoft.AspNetCore.Identity

@model AnimeApp.Models.Anime

<head>
    <link rel="stylesheet" href="~/css/mystyles.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.18.0/font/bootstrap-icons.css">
</head>

<body>
    <div class="content">
        <div class="inner-content">
            <div class="header">
                <div class="anime-wraper">
                    <img class="anime-cover" src="@Model.CoverUrl" alt="Монстр" />
                    <div class="anime-info">
                        <div class="anime-title"> @Model.Title </div>
                        <div class="anime-release-year"> @Model.ReleaseYear </div>
                        <div class="anime-description"> @Model.Description</div>
                    </div>
                    <button asp-controller="Animes" asp-action="AddAnimeToUser" formmethod="get" class="btn-watched" id="watchButton" data-anime-id=@Model.AnimeId>Буду смотреть</button>
                    <h1>AnimeId = @Model.AnimeId</h1>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="/js/watch_button.js"></script>

AnimeApp/Views/Animes/Index.cshtml
@model IEnumerable<Anime>
@{
    ViewData["Title"] = "Index";
}

<head>
    <link rel="stylesheet" href="~/css/mystyles.css"/>
</head>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th style="text-align:center; width:130px">
                Anime Title
            </th>
            <th style="text-align:center; font-size:large">
                Description
            </th>
            <th style="text-align:center; vertical-align:middle;width:150px">
                Release Year
            </th>
            @if (User.IsInRole("Admin"))
            {
                <th style="text-align:center; vertical-align:middle;width:150px">
                    Actions
                </th>
            }
        </tr>
    </thead>
    @if(User.IsInRole("Admin"))
    {
        <a type="submit" class=" btn btn-dark btn-lg mt-5" asp-controller="Admin" asp-action="AddNewAnime">Add Anime</a>
    }
    
    <form asp-action="Index" method="get" >
        <div class="input-group mt-2 mb-5">
            <input type="text" name="SearchString"  value="@ViewData["CurrentSearchString"]" class="form-control" placeholder="Search your anime!"/>
            <input type="submit" value="Search" class="btn btn-dark btn-lg" 
                style="font-size:18px; font-weight:400"/>

            </div>


    </form>

    <tbody>
        @foreach (var obj in Model)
        {
            <tr> 
                <td style="text-align: center; vertical-align: middle;">
                    <a asp-action="Anime" asp-route-animeId="@obj.AnimeId" class="nav-link">@obj.Title</a>
                </td>
                <td>
                    @obj.Description
                </td>
                <td style="text-align: center; vertical-align: middle;">
                    @obj.ReleaseYear
                </td>
                @if (User.IsInRole("Admin"))
                {
                <td style="text-align: center; vertical-align: middle; width:50px">
                    <div class="btn-group btn-group-sm" role="group">
                            <a asp-controller="Admin" asp-action="DeleteAnime" asp-route-animeId="@obj.AnimeId" class="btn btn-primary delete-anime">
                                <i class="bi bi-trash3"></i>
                            </a>

                        <a asp-controller="Admin" asp-action="Edit" asp-route-animeId="@obj.AnimeId" class="btn btn-primary">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                    </div>
                </td>
                    
                }
            </tr>
        }
    </tbody>

</table>